[Feat] Add shiftKey modifier to some events
dmtrKovalenko/cypress-real-events pull request #514
Opened 2023-07-09 16:36 UTC by Minilfat

### Motivation
I faced issue that it wasn't possible to do smth like: 
```ts
cy.realPress('ShiftLeft', {pressDelay: 1000})
cy.get('#some-id').realClick() // <-- the shift key already released 
// then unpress it somehow
```
Cypress synthetic events come with `shiftKey: boolean` property in some events where it makes sense. 
I think it's useful to have the same option for real events too. 

### Notes
I decided to write test cases in separate file for 2 main reasons: 
- there are few more modifiers that can be added in future and it makes sense to test them in the same `modifiers` test  suite imho
- I couldn't find any events that would react differently when shift key was pressed when event occurred, so had to write simple cases myself

2023-07-09 18:06 UTC, dmtrKovalenko requested changes
Thanks for adding this. Couple comments

* I don’t see that you modified real mouse up
* please revert all the unrelated style changes

2023-07-10 07:25 UTC, Minilfat commented
@dmtrKovalenko thanks for review! I addressed all comments you left, let me know if I need to change something else

2023-07-17 17:40 UTC, dmtrKovalenko approved these changes

2023-07-17 17:40 UTC, merged

2023-08-03 11:24 UTC, dmtrKovalenko commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/cypress-real-events/v/1.10.0)
- [GitHub release](https://github.com/dmtrKovalenko/cypress-real-events/releases/tag/v1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: